spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/day4
    username: root
    password: new_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
server:
  port: 8082
