spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingcart
    username: root
    password: nguyenDeo@19992000!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081

# Custom feature property for AppConfig
my:
  feature:
    enabled: true
    value: "This is a YAML-based feature value"
# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  pathsToMatch:
    - /api/v1/**
  info:
    title: "Shopping Cart API"
    version: "1.0.0"
    description: "Spring Boot REST API for Shopping Cart application."
