spring:
  datasource:
    url: jdbc:mysql://localhost:3306/phucdb?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 77777
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
